# Generated by Django 4.2.2 on 2023-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookstoremodel_cover_image_alter_bookstoremodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='book_name',
            field=models.CharField(max_length=40),
        ),
    ]
