# Generated by Django 4.2.2 on 2023-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookstoremodel_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
